from detectron2.config import CfgNode as CN


def add_model_2d_config(cfg):
    cfg.MODEL.DINO = CN()
    cfg.MODEL.DINO.REPO_NAME = "facebookresearch/dinov2"
    cfg.MODEL.DINO.MODEL_NAME = "dinov2_vits14_reg"
    cfg.MODEL.MODEL_2D = CN()
    cfg.MODEL.MODEL_2D.SIZE_DIVISIBILITY = 32
    cfg.MODEL.MODEL_2D.TRAIN_NUM_SAMPLES = 80000
    cfg.MODEL.MODEL_2D.MIN_INSTANCE_PIXELS = 200
    cfg.MODEL.MODEL_2D.NO_FPN = False
    cfg.MODEL.MODEL_2D.FEATURE_DIM = 256

    cfg.INPUT.DATASET_MAPPER_NAME = "front3d"
    cfg.INPUT.COLOR_AUG_SSD = False
    cfg.INPUT.CROP.SINGLE_CATEGORY_MAX_AREA = 1.0
    cfg.INPUT.SIZE_DIVISIBILITY = -1

    cfg.INPUT.RANDOM_INST_MASK = CN()
    cfg.INPUT.RANDOM_INST_MASK.ENABLED = False
    cfg.INPUT.RANDOM_INST_MASK.MASK_PATH = None
    cfg.INPUT.RANDOM_INST_MASK.PROB = 0.0
    cfg.INPUT.RANDOM_DEPTH_NOISE = False
    cfg.INPUT.PSEUDO_DEPTH = CN()
    cfg.INPUT.PSEUDO_DEPTH.ENABLED = False
    cfg.INPUT.PSEUDO_DEPTH.DEPTH_PATH = None

    cfg.SOLVER.OPTIMIZER = "ADAMW"
    cfg.SOLVER.BACKBONE_MULTIPLIER = 1.0
    cfg.SOLVER.WEIGHT_DECAY_EMBED = 0.0


def add_depr_config(cfg):
    ## 3D reconstruction configs
    cfg.MODEL.PROJECTION = "CubeForwardProjection"

    cfg.MODEL.TRIPLANE_VAE = CN()
    cfg.MODEL.TRIPLANE_VAE.DIMENSIONS = 32
    cfg.MODEL.TRIPLANE_VAE.KL_STD = 0.25
    cfg.MODEL.TRIPLANE_VAE.PLANE_SHAPE = [3, 32, 128, 128]
    cfg.MODEL.TRIPLANE_VAE.Z_SHAPE = [2, 32, 32]
    cfg.MODEL.TRIPLANE_VAE.NUM_HEADS = 16
    cfg.MODEL.TRIPLANE_VAE.TRANSFORM_DEPTH = 1
    cfg.MODEL.TRIPLANE_VAE.STAT_PATH = None
    cfg.MODEL.TRIPLANE_VAE.MLP_PATH = None
    cfg.MODEL.TRIPLANE_VAE.PRETRAINED_PATH = None
    cfg.MODEL.TRIPLANE_VAE.EXTRUDE_DEPTH = 0.0

    cfg.MODEL.TRIPLANE_DIFFUSION = CN()
    cfg.MODEL.TRIPLANE_DIFFUSION.PRETRAINED_PATH = None
    cfg.MODEL.TRIPLANE_DIFFUSION.SCHEDULER_CONFIG = None  # unused
    cfg.MODEL.TRIPLANE_DIFFUSION.ENABLE_ATTN = False
    cfg.MODEL.TRIPLANE_DIFFUSION.CFG_PROB = 0.0
    cfg.MODEL.TRIPLANE_DIFFUSION.EMBED_MEAN = 0.0
    cfg.MODEL.TRIPLANE_DIFFUSION.EMBED_STD = 1.0
    cfg.MODEL.TRIPLANE_DIFFUSION.SDF_WEIGHT = 5.0
    cfg.MODEL.TRIPLANE_DIFFUSION.SUR_WEIGHT = 10.0
    cfg.MODEL.TRIPLANE_DIFFUSION.NOR_WEIGHT = 5.0
    cfg.MODEL.TRIPLANE_DIFFUSION.EIK_WEIGHT = 0.5
    cfg.MODEL.TRIPLANE_DIFFUSION.MSE_WEIGHT = 1.0

    cfg.GLOBAL.EMPTY_CACHE_BEFORE_STEP = False
